platform :ios, '8.3'

use_frameworks!
inhibit_all_warnings!

target 'AnimatedTextInput_Example' do
    pod 'AnimatedTextInput', :path => '../'
end

target 'AnimatedTextInput_Tests' do
    pod 'AnimatedTextInput', :path => '../'
    pod 'KIF', '~> 3.5'
    pod 'FBSnapshotTestCase'
end
